version: 0.2

env:
  variables:
    CLUSTER_NAME: "my-cluster"
    REGION: "ap-south-1"
    REPO_NAME: "eks_repo"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$REGION.amazonaws.com
      - echo "Installing Helm..."
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - echo "Tagging Docker image..."
      - docker tag $REPO_NAME:$IMAGE_TAG $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo "Creating IAM Service Account for ALB Controller..."
      - eksctl create iamserviceaccount --cluster "my-cluster" --namespace kube-system --name aws-load-balancer-controller --attach-policy-arn "arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/AWSLoadBalancerControllerIAMPolicy" --approve --override-existing-serviceaccounts
      - echo "Downloading AWS Load Balancer Controller CRDs..."
      - wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
      - echo "Applying AWS Load Balancer Controller CRDs..."
      - kubectl apply -f crds.yaml
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo update
      - helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller --namespace kube-system --set clusterName=$CLUSTER_NAME --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
      - echo "Deploying application..."
      - kubectl apply -f deployment.yml
      - kubectl apply -f service.yml
      - kubectl apply -f ingress.yml

