version: 0.2

env:
  variables:
    CLUSTER_NAME: "my-cluster"
    AWS_REGION: "ap-south-1"
    ALB_SERVICE_ACCOUNT: "aws-load-balancer-controller"

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing AWS CLI, kubectl, eksctl, and Helm..."
      - curl -sSL "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3" | bash
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

  pre_build:
    commands:
      - echo "Checking IAM OIDC provider for EKS..."
      - eksctl utils associate-iam-oidc-provider --region $AWS_REGION --cluster $CLUSTER_NAME --approve || echo "OIDC already exists"
      
      - echo "Creating IAM policy for ALB Controller..."
      - curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
      - aws iam create-policy --policy-name AWSLoadBalancerControllerIAMPolicy --policy-document file://iam-policy.json || echo "Policy exists"

      - echo "Creating Service Account for ALB Controller..."
      - eksctl create iamserviceaccount \
          --cluster $CLUSTER_NAME \
          --namespace kube-system \
          --name $ALB_SERVICE_ACCOUNT \
          --attach-policy-arn arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/AWSLoadBalancerControllerIAMPolicy \
          --approve || echo "Service account exists"

  build:
    commands:
      - echo "Adding Helm repository for ALB Controller..."
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo update

      - echo "Installing AWS Load Balancer Controller..."
      - helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
          -n kube-system \
          --set clusterName=$CLUSTER_NAME \
          --set serviceAccount.create=false \
          --set serviceAccount.name=$ALB_SERVICE_ACCOUNT

  post_build:
    commands:
      - echo "Verifying ALB Controller Pods..."
      - kubectl get pods -n kube-system | grep aws-load-balancer-controller
      
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yml
      - kubectl apply -f ingress.yml
