apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app  # This must match the labels inside `template.metadata.labels`
  template:
    metadata:
      labels:
        app: my-app  # Must match `selector.matchLabels`
    spec:
      containers:
      - name: my-app
        image: 235494789903.dkr.ecr.ap-south-1.amazonaws.com/eks_repo:latest
        ports:
        - containerPort: 80
